### ISSUE TITLE
Feature Request: Time in different locations

### ISSUE THREAD

**Issue by markcs** [ueffel/Keypirinha-Time#1]
Hi!

I was looking for a plugin that would show me the time in different locations.  Something like 'Time:  Singapore' or 'Time:  New York'.  This could use the open API http://worldclockapi.com/ or https://timezonedb.com/

However, if that is not possible, it would be great if the user could configure this plugin with selected names and time zones?

**Comment by ueffel** [comment]
I see want I can do.

**Comment by ueffel** [comment]
I found an approach that does not use any webservice. Have look at the new release :)

Also I recommend an update to Keypirinha v2.21.

**Comment by Avastgard** [comment]
Does this approach account for daylight saving time?

**Comment by ueffel** [comment]
It should. It relies on the timezone data from the dateutil library
