### ISSUE TITLE
Time creates some exceptions

### ISSUE THREAD

**Issue by DrorHarari** [ueffel/Keypirinha-Time#2]
Time creates some exceptions. For example entering 123:

![time-exceptions](https://user-images.githubusercontent.com/1831901/48667076-fb9be900-ead6-11e8-81c2-14b0bf7f3530.png)

I would have expected typing smaller numbers (including 0) to show me the epoch time (or later).

**Comment by ueffel** [comment]
hm. Well the timestamps don't work well if they are smaller than 86400. Maybe I should do a bit more exception handling...
