### ISSUE TITLE
Is it possible to include more cities to the timezone search?

### ISSUE THREAD

**Issue by Avastgard** [ueffel/Keypirinha-Time#4]
My main use case for this is to check the time zone difference on certain cities.

However, the cities I usually look up are included in another city's time zone. For example, searching for "Milwaukee" on Time shows nothing, as there is no specific entry for it because it falls under "US/Central Time" (UTC -5). If you are not looking for the time in a city that is already on the Timezone database, you just have to know at what timezone the city is, which defeats the purpose of this plugin. So I end up just googling "Milwaukee time" instead, as it's much faster.

I would like to know if it's possible to add more cities to the database and if I can do this by myself.

EDIT: Also, does the plugin account for daylight saving time?

**Comment by ueffel** [comment]
The timezone step now searches the input via an online API to get a location and the respective timezone. Sadly, there is no viable offline approach to achieve this. That means there is some delay after entering a search term (location name) and displaying the searched timezone.

**Comment by Avastgard** [comment]
I'm not sure I understand how this is supposed to work now. I updated `keypirinha-time` through PackageControl update. Then I typed `Timezone:` > `New York` `Enter`, but nothing happens. Am I doing something wrong?

**Comment by ueffel** [comment]
You may need to restart keypirinha because I updated the third party libraries.

it should look like this.
![image](https://github.com/user-attachments/assets/427a22b1-a1e4-4751-8592-3002c231acb2)

Edit: Pressing <kbd>Enter</kbd> after entering the search term is not needed to start searching.

**Comment by Avastgard** [comment]
Sweet, restarting it got it working. Thanks!
